### ISSUE TITLE
List up objects appeared in current view

### ISSUE THREAD

**Issue by theTIOM** [xBimTeam/XbimWebUI#109]
Hi, I'm trying to present a list of object which appeared in current view.
Hence, I investigated your viewer script file and found some relevant things.

setcameraposition, getcameraposition, perspectivecamera

using getcameraposition, I can get the coordinate information, although it is not very accurate.
(when I inserted those values using setcameraposition function, viewer presented different views and coordinates. this is another question. how can I get a current direction vector value with current coordinate values.)
anyway, I found fov, near, and far attributes in perspectivecamera class and it means I can calculate view frusrum using those values. 

but I don't know what is the meaning of each value. I saw that fov value is fixed as 95, and far and near values mean cutting planes and it would be integer values. moreover, I don't know what is the next step. I mean if I succeed calculate view frusrum info, how can I indentify objects which located in these areas. could you give me any suggestions?

**Comment by martin1cerny** [comment]
Try using [zoomTo(id)](http://xbimteam.github.io/XbimWebUI/xViewer.html#zoomTo) function. That will do what you want. I wouldn't recommend to zoom to group of objects because if they are small and distributed all over the place it will zoom to the view where possibly nothing is identifiable and hence user will assume it is didn't work.

**Comment by theTIOM** [comment]
Thanks for your response. Actually, I solved this problem based on this code "id = viewer._getID(viewX, viewY);" today. However, I am still facing with one major problem.  "getcameraposition" function.

When I tried to get the camera position at the point, as shown in below image link, the getcameraposition function presented the value, (29697.6171875, 4331.068359375, 13167.69140625).
https://www.dropbox.com/s/hd3tl2vq7p9jd2k/11.png?dl=0

However, when I inserted these values using setcameraposition function, the viewer presented incorrect view, as shown in below image link.
https://www.dropbox.com/s/pebehcakhdx3pts/22.png?dl=0

How can I resolve it?

**Comment by martin1cerny** [comment]
Documentation is probably not clear enough about this but [setCameraPosition()](http://xbimteam.github.io/XbimWebUI/xViewer.html#setcameraposition) is changing the view so that the camera position is what you set and camera target is what you se with [setCameraTarget()](http://xbimteam.github.io/XbimWebUI/xViewer.html#setCameraTarget) which takes id of the object and uses centroid of its bounding box as a target of the view. If you want to reconstruct the view exactly as it is you can use a private member [viewer._mvMatrix](https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/xbim-viewer.debug.js#L195) which holds the full view transformation matrix.
