### ISSUE TITLE
Rendering issue (scene flickering when rotate/zoom)

### ISSUE THREAD

**Issue by przemwo** [xBimTeam/XbimWebUI#113]
Hi,

When I view a .wexbim model ([models.zip](https://github.com/xBimTeam/XbimWebUI/files/524770/models.zip)) in Chrome/FireFox using XbimWebUI and try to rotate/zoom the camera, scene flickers and disappears (see: http://g.recordit.co/9xfGKFNLCn.gif).

![9xfgkfnlcn](https://cloud.githubusercontent.com/assets/7883624/19312796/43339136-9094-11e6-9cc1-e246b243d771.gif)

Launching Chrome with the following command fixes the issue:
`chrome.exe --use-gl=desktop`

For FireFox I have to set the `webgl.disable` option to `true` to make it work.

I used Xbim Xplorer to convert .ifc file into .wexbim.

Do you know if this can be solved in XbimWebUI/SceneJS without the need to adjust browser settings upfront?

**Comment by GrzegorzBlok** [comment]
To add to what my colleague  @przemwo wrote. We convert ifc file to wexbim using following packages:
```
<package id="Xbim.Essentials.4" version="4.0.1" targetFramework="net46" />
<package id="Xbim.Geometry.4" version="4.0.5" targetFramework="net46" /> 
```
and the following code:
```
using (var m = IfcStore.Open("OPG34001-4.ifc"))
{
    var geomContext = new Xbim3DModelContext(m);
    geomContext.CreateContext();

    using (var wexBiMfile = new FileStream("OPG34001-4.wexBIM", FileMode.Create, FileAccess.Write))
    {
        using (var bw = new BinaryWriter(wexBiMfile))
        {
            m.SaveAsWexBim(bw);
            bw.Close();
        }

        wexBiMfile.Close();
    }
}
```

The only workaround we found is disabling ANGLE, unfortunately it is not feasible for widely accessible web page to require all users to do it.

**Comment by milocihou** [comment]
Hi @GrzegorzBlok ,
How can I the property *.json file by using IfcStore?

**Comment by martin1cerny** [comment]
Hi @przemwo and @GrzegorzBlok . I understand that tinkering with browser inner settings is not acceptable. However, we haven't done any substantial changes and this is the first report of this kind of behaviour. Because it is a problem both in Chrome and Firefox it is not a problem of specific browser implementation but it can still be down to specific GPU on your computer. As you probably know WebGL uses HW acceleration but it doesn't access GPU directly. Many implementations use middle tiers like ANGLE. If disabling of ANGLE made it work it makes me think the problem might be in there. But I'd like to test it on my PC. Can you provide us with the sample data? Preferably as an IFC file?

P.S. to @przemwo: XbimWebUI doesn't use SceneJS or any other WebGL library. It uses WebGL directly.

**Comment by GrzegorzBlok** [comment]
Hi @martin1cerny,

This is sample data that makes the problem visible:
[Small model.zip](https://github.com/xBimTeam/XbimWebUI/files/526375/Small.model.zip)

Two things are worth noting. Example data (i.e. SampleHouse.wexbim) available with xViewer works perfectly. The scene flickering/disappearing frequency differs from computer (and GPU) to computer, but it is always there. The bigger, more complex model the worse it gets.

**Comment by martin1cerny** [comment]
The problem is in the precision of WebGL and offset of your models from the origin. Because coordinates in your model are around [298 000 m ,6 696 000 m] all transformations happen very far away from the origin and that is most possibly causing the flickering effect. It is possible that disabling ANGLE might increase the precision. xBIM should adjust it by default. This is an optional argument in `geomContext.CreateContext()` but I've just checked and it doesn't take any effect now. Will check with my colleagues and get back to. You will than need to bare in mind that if you do any coordinates measurements in the resulting wexBIM file it will give you **different** coordinates than you have in the IFC file.

**Comment by GrzegorzBlok** [comment]
HI @martin1cerny,

Thank you for you answer and help. We really appreciate it.

We noticed one more thing - if we use orthogonal view then the rotation works fine, i.e. no flickering is visible. In orthogonal view we can't zoom, though.

@przemwo wrote that scene flickers and disappears during rotating/zooming. In fact, flickering is visible only during rotating in perspective view. The zooming works fine.

**Comment by martin1cerny** [comment]
I'd assume the reason is still the same. Perspective matrix is more complex than orthogonal matrix so it will behave differently. Also navigation in orthogonal projection is not properly implemented now. We should probably mark it as a known issue somewhere. Feel free to contribute with this kind of functionality.

**Comment by mahmouds12** [comment]
Any news about the flickering issue when at Perspective mode?

**Comment by przemwo** [comment]
There was some problem with the .wexbim model we had. We got another one and everything worked as expected.

**Comment by simiii** [comment]
We also have a similar problem with the attached model: 
[Model.zip](https://github.com/xBimTeam/XbimWebUI/files/6967932/5.00.-.Modell.reduziert.Test.zip)

![Problem-Flickering](https://user-images.githubusercontent.com/5853121/129021681-3e319ccb-e12c-425e-9e48-75952fe2f3bd.gif)

The cartesian points don't seem to be very large e.g. 
`#607470= IFCCARTESIANPOINT((0.0395000725656,0.0729369504997,0.16397882523));`

Should I open a new Issue?

**Comment by simiii** [comment]
I open a new ticket
