### ISSUE TITLE
Bounding box representation

### ISSUE THREAD

**Issue by dbojadievski** [xBimTeam/XbimWebUI#123]
I've noticed every product map contains a bounding box represented with give floating-point numbers. I am not familiar with any representation of the kind; could you explain the representation to me? 

Thank you very much!

Best regards,
Dino.

**Comment by martin1cerny** [comment]
It is always 6 floating points which is X, Y, Z of the minimal point and sizes in X, Y, Z directions.

**Comment by dbojadievski** [comment]
I'm really not familiar with that representation at all. Could you link me to a reasonable explanation?

**Comment by martin1cerny** [comment]
It is [axis-aligned minimum bounding box](https://en.wikipedia.org/wiki/Minimum_bounding_box). 

I also realized that you have created your own [Spacker utility](https://github.com/dbojadievski/Spacker) which is clearly based on [my code of Spacker](https://github.com/xBimTeam/XbimWebUI/tree/master/Utilities/ShaderPacker) which is a part of xBIM Toolkit and is published under [CDDL license](https://github.com/xBimTeam/XbimWebUI/blob/master/LICENCE.md). That doesn't allow to do what you did with our code. So I'd like to inform you that it is illegal. I am the original author of this SW which is clear from the [GitHub commit log](https://github.com/xBimTeam/XbimWebUI/commits/master/Utilities/ShaderPacker/Program.cs). As such you have to made it clear in every file you have taken. Here is an extract from the license: 

### 3.1. Availability of Source Code.

Any Covered Software that You distribute or otherwise make available in Executable form must also be made available in Source Code form and that **Source Code form must be distributed only under the terms of this License. You must include a copy of this License with every copy of the Source Code form of the Covered Software You distribute or otherwise make available.** Yo must inform recipients of any such Covered Software in Executable form as to how they can obtain such Covered Software in Source Code form in a reasonable manner on or through a medium customarily used for software exchange.

### 3.2. Modifications.

The **Modifications that You create or to which You contribute are governed by the terms of this License.** You represent that You believe Your Modifications are Your original creation(s) and/or You have sufficient rights to grant the rights conveyed by this License.

### 3.3. Required Notices.

You must **include a notice in each of Your Modifications that identifies You as the Contributor of the Modification**. You may not remove or alter any copyright, patent or trademark notices contained within the Covered Software, or any notices of licensing or any descriptive text giving attribution to any Contributor or the Initial Developer.

**Comment by dbojadievski** [comment]
Thanks for the information! It's much appreciated.

Regarding Spacker - it's based off yours, yes. I thought I've included a note mentioning you as the author of the original? Do forgive the foresight; mistakes do tend to happen every now and then. I'll take a look at rectifying this particular one immediately. 

P.S Would you consider accepting a pull request with the changes I've made?

**Comment by martin1cerny** [comment]
It is all right if you fix license requirements. I'm happy to accept pull requests which will improve xBIM. However, this is a single purpose utility where your extended functionality would most probably not actually change/improve the result in WebUI. If you think it would I'm happy to merge it in.

**Comment by dbojadievski** [comment]
No, I don't think it will improve the result in WebUI at all; however, I do think it's particularly useful in other kinds of tasks. I use it in development of some other works on other platforms. 

I fixed those license requirements. Sorry for the mishap again.
