### ISSUE TITLE
Adopting Node / npm build & packaging 

### ISSUE THREAD

**Issue by andyward** [xBimTeam/XbimWebUI#137]
Having had a look at the latest Typescript, webpack and npm work on `develop`, in order to build a Nuget package it struck me that we might be better off adopting _npm_ as the packaging (and dependency manager) for this particular repo. There's no direct .NET dependencies or outputs (aside from the build tooling in Utilities) so we could achieve more reach on this web library decoupling from the Visual Studio build & packaging.

Even if we continue to support both packaging solutions, I think we may want to adopt some of the NodeJS build patterns. E.g. Currently we're transpiling Typescript to JS along side the TS source, rather than into a `/dist` folder from, say, `/src`. The current approach seems messy as we're then versioning intermediate generated code (or we're going to have to gitignore some JS). Equally if we're using node, we could also use it to bootstrap (ts, ts-loader etc), and bring in the Libs (gl-matrix, SystemJS etc)

i.e. should we go 'all in' on NodeJS tooling, rather than the 'hybrid' solution we currently have?

**Comment by martin1cerny** [comment]
I did consider this and @GeorgDangl has already suggested that he would like to do it. I have very limited experience with *npm*. Talking about dependencies there is no deployment dependency at all right now. I have refactored *gl-matrix* to typescript so it is embedded in our code. We only use a limited subset of the library. *SystemJS* is also not a deployment dependency because final packages are packed as UMD which allows to use them as plain JavaScript as well as modules loaded by *SystemJS* or *Require*.

To round it all up: all dependencies in the project are just development dependencies. Final result is a set of independent UMD packages. So we should be able to produce easily both NuGet and *npm* packages. I think it makes sense to publish NuGet package as well because that is our main publishing platform.

**Comment by andyward** [comment]
Cool. Sounds like it's still work in progress at the moment so we've got a few of the old dependencies around. 

Offering an npm package will be beneficial I think. I've created us an npmjs 'xbimteam' organisation anyway just so we've grabbed the name (https://www.npmjs.com/org/xbimteam/). If you've got a npmjs account I'll make you an owner @martin1cerny , @GeorgDangl?

I guess whether we use more of the NodeJS tooling to build & create packaging is something we need to decide on. Currently we're using MsBuild/VS to invoke nodeJS build commands via a batch file (for webpack etc) - which is a little clunky IMO. George seems to have a nice build setup at https://github.com/GeorgDangl/xbim-meets-angular 😄

**Comment by GeorgDangl** [comment]
@andyward , I'm `georgdangl` on npmjs.org.

That project currently references the XBimWebUI project via file reference (`"xbim-webui": "file:../../XbimWebUI/Xbim.WeXplorer"`) and everything seems to work, so it should be quite easy to publish to the npm registry.

I think we can have the build process as-is, just add a .npmignore to specifiy the content of the packeg and do a manual (or batch-file=) `npm publish`.

I'll update my demo this weekend, make sure everything works and will then submit a pull request!

**Comment by GeorgDangl** [comment]
I now got it working as npm module, but had to tinker a bit.
`Beautiful code |--------X-| At least it works`

Demo is here: [http://xbim-web.dangl.me](http://xbim-web.dangl.me)

I've created an [npm publish branch](https://github.com/GeorgDangl/XbimWebUI/commits/feature/npm-publish) in my fork where I had to alter a few things to get it working:

Entry files `xbim-viewer.ts` and `xbim-browser.ts` for the webpack bundle generation were added (the generated `*.d.ts` files didn't work for me since not all symbols were imported). I've also had to add `typescript`, `@types/node` and `ts-loader` dependencies so it could be built without Visual Studio.

Now to actually use it in a project, I included it as package `xbim-webui` ([currently from the file path](https://github.com/GeorgDangl/xbim-meets-angular/blob/master/src/xBimMeetsAngular/package.json#L56)).

Imports now look like this:
```typescript
import { Viewer } from 'xbim-webui/xbim-viewer';
import { Browser } from 'xbim-webui/xbim-browser';
```

It could be further shortened to `import { } from 'xbim-webui'` by defining an `index.ts` that exports from borth `xbim-viewer` and `xbim-browser`, but I'm not sure if it would be actually preferred to have two separate packages in npm, `xbim-viewer` and `xbim-browser` (with the browser having a dependency on `xbim-viewer`).

Oh, and I had a bit of trouble with building from a fresh clone, so I'd really appreciate some feedback on that as well=) Would be great if you could try to clone the [npm publish branch](https://github.com/GeorgDangl/XbimWebUI/commits/feature/npm-publish) to a new repository and build it.

Things to do before being able to release on npm:

- [ ] Verify that build works both via Visual Studio and npm
- [ ] Copy the Readme before publishing to npm (e.g. via a publish script)
```powershell
$readme = Join-Path -Path (Get-Item $PSScriptRoot).Parent.FullName -ChildPath "README.md"
Copy-Item -Path $readme -Destination "$PSScriptRoot\README.md"
& npm publish
Remove-Item -Path "$PSScriptRoot\README.md"
```

**Comment by andyward** [comment]
Nice work! Will give it a test later this week on a clean environment to check it out! 

Lol: "At least it works"

**Comment by GeorgDangl** [comment]
Hey there, just FYI, I got a bit better at creating npm modules, so I'll try to optimize the solution in the next few days and will report again. Hope we can then get an npm package published=)

**Comment by martin1cerny** [comment]
Hi Georg,
this is great news. Looking forward to hearing more :-)

Martin

**Comment by GeorgDangl** [comment]
So, took me a bit longer to find time for this, but I've updated it a bit, currently on the `npm-publish` branch in [my fork](https://github.com/GeorgDangl/XbimWebUI/tree/feature/npm-publish).

There's now a top-level `build.ps1` script in the solution which should work out of the box on a clean install, the only requirements are right now Visual Studio 2017 (could be downgraded to VS2015 I think, but it's adoption is quite large already afaik) and npm on the build computer.

As for the package distribution, I've adopted to split it in two packages, `xbim-viewer` and `xbim-browser`. When configuring npm packages in `package.json`, there should be an entry pointing to the main script, and this is required to be a single file. That means if it's only a single package, the browser is also included in the bundle even if it's not necessary.

Typings, IntelliSense etc. are all working. Here's an example of using the Viewer in an Angular Component (shortened):

```typescript
import { Viewer } from 'xbim-viewer';

@Component()
export class ViewerComponent implements AfterViewInit {

  constructor(private modelsService: ModelsService) { }

  private viewer: Viewer;
  @ViewChild('viewer') viewerCanvas: ElementRef;
  private modelLoadedSubscription: Subscription;
  private loadedModels: { [modelId: string]: number } = {};

  ngAfterViewInit() {
    this.viewer = new Viewer(this.viewerCanvas.nativeElement);
    this.viewer.start();
    this.viewer.on('loaded', (event: { id: number, tag: string }) => this.loadedModels[event.tag] = event.id);
    this.modelLoadedSubscription = this.modelsService.modelLoaded.subscribe(m => {
      this.viewer.load(m.geometry, m.modelId);  
    });
  }
}
```

To reference the package in your `package.json`, you currently need to have it on your disk and have run the build command, then:

```json
{
  "dependencies": {
    "xbim-viewer": "file:../../submodules/XbimWebUI/Xbim.WeXplorer/npm_bundle_output/xbim-viewer"
   }
}
```

I would appreciate some feedback, especially if the build and referencing works=)

**Comment by martin1cerny** [comment]
I'll definitely have a look.

**Comment by GeorgDangl** [comment]
Hey @martin1cerny, any updates on going forward with npm and TypeScript yet?

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer).
