### ISSUE TITLE
ID from WEXBIM and IFCXML file

### ISSUE THREAD

**Issue by SBersani** [xBimTeam/XbimWebUI#143]
Hi all,
I converted and ifcxml file into a wexbim file but the ID that I find in the model doesn't correspond to the id of the ifcxml file.
I used this instructions:

viewer.on("pick", function (arg) {
var span = document.getElementById("id");
if (span) {
span.innerHTML = arg.id;
};
});

Is it wrong?
Thanks in advance,
Best regards.
Silvia

**Comment by martin1cerny** [comment]
Which ID do you expect to see in there? The number you get from the viewer
is EntityLabel you get from xBIM. This is guaranteed to match. The only
problem might be if the number is too high and your GPU precision is not
good enough in which case the number you get from the viewer might get
distorted. Can you post a sample data and code to demonstrate the problem?

Dne 13. 7. 2017 16:17 napsal uživatel "SBersani" <notifications@github.com>:

**Comment by SBersani** [comment]
Hi Martin,
here attached you can find the IFCXML file: if I select the element (see the blue arrow) the program returns ID = 303103, but in IFCXML file this ID doesn't exist.

[sample_project_TestIFCXML.zip](https://github.com/xBimTeam/XbimWebUI/files/1147563/sample_project_TestIFCXML.zip)

![image](https://user-images.githubusercontent.com/30153221/28201727-a468e4d6-6872-11e7-8cbe-db5a24fc3d03.png)

Thanks!
Silvia

**Comment by martin1cerny** [comment]
I see. We don't use identifiers from XML as EntityLabels because nothing
guarantees that these will be convertible to numbers. If you try to find it
in the model when it is being processed you will find it in there as
`model.Instances[EntityLabel]`.

Dne 14. 7. 2017 9:31 napsal uživatel "SBersani" <notifications@github.com>:

**Comment by martin1cerny** [comment]
By the way, using XML to save IFC is not very good idea for several reasons. STEP encoding is a lot more conscious and implementation of STEP reader can use minimal memory as opposed to XML where it has to load the complete model in memory (yes, I know you can read XML with forward only readers but complex structure of IFC schema doesn't allow to take full advantage of this because it is multidirectional object graph, not a hierarchical document). 

If my previous comment resolved your issue, can you close it please?

**Comment by SBersani** [comment]
Yes Martin, 
many thanks for your help!
