### ISSUE TITLE
Unable to view 3D Model [Getting CORS policy error].

### ISSUE THREAD

**Issue by fouziyapatel** [xBimTeam/XbimWebUI#171]
Hello,
I'm unable to view 3D model. After further debugging I'm getting  below mentioned error : 

> Uncaught Failed to fetch semantic JSON data from server. Server code: 404. This might be due to CORS policy of your browser if you run this as a local file.

and after sometime it takes me to another error as mentioned though Wexbim file got generated successfully.

> this combination of attachments does not work

Kindly help me to know what modifications would be required to get this model rendered. Please find attached file.
[ModelIFC(wexbim).zip](https://github.com/xBimTeam/XbimWebUI/files/1780472/ModelIFC.wexbim.zip)
[ModelIFC.zip](https://github.com/xBimTeam/XbimWebUI/files/1780473/ModelIFC.zip)

Thanks.

**Comment by martin1cerny** [comment]
Try to put JSON file URL into web browser address bar to see if you can get it. If you can't get to it neither can the viewer. Make sure your web server serves JSON files as static files.
WebGL error might signal insufficient WebGL capabilities of your browser.

**Comment by Dhruti03** [comment]
Hello @martin1cerny,
I have two queries as mentioned : 
1) I don't have clarity on how to check for JSON file in url and how to find whether web server serves JSON files as static files. Is it possible to share some reference?
2) Few models are getting rendered properly but in few models it takes me to 'WebGL support is insufficient'. Is it something like WebGL requirement differs from model to model.

Thanks.

**Comment by martin1cerny** [comment]
Add 1) You pass a URL of the JSON file to the viewer in your code somewhere. Make sure you get the file if you paste that URL in the browser address bar.
Add 2) Your model must be **very** detailed. It has 172 065 810 indices. That simply makes WebGL to crash because it is overloaded by the amount of data. That leads to lost WebGLContext and it propagates as an inability to create a framebuffer because it can't operate without a valid WebGL context.

Your IFC is a Tekla model which I like because it creates concise IFC with nice parametric geometry. But when this is converted to triangles for a visual presentation it is huge. I tried and even desktop viewers which are normally very performant struggle. It is a reinforcement steel in this case:
![image](https://user-images.githubusercontent.com/773078/37095606-afccf994-2216-11e8-8dff-df6a3a7ce676.png)
