### ISSUE TITLE
uncaught exception: Failed to fetch semantic JSON data from server. Server code: 404. This might be due to CORS policy of your browser if you run this as a local file.

### ISSUE THREAD

**Issue by dhundaleamol** [xBimTeam/XbimWebUI#2]
I am using XbimWebUI-master source ,And try to convert this source in MVC ,then I got this error as follows .
"uncaught exception: Failed to fetch semantic JSON data from server. Server code: 404. This might be due to CORS policy of your browser if you run this as a local file."

This error is occur in xbim,browser,js ..

Can someone help me ?

**Comment by LloydPickering** [comment]
Are you running using a webserver (eg IIS or IIS Express) or from a folder on your local computer? I won't work running outside of a webserver

**Comment by dhundaleamol** [comment]
i am using IIS locally in my pc

**Comment by LloydPickering** [comment]
OK, so it's probably not a CORS policy problem, it's more likely it can't find the semantic JSON file. Martin might be able to help out, but I think you need to generate both a .wexbim and a semantic json file.

**Comment by dhundaleamol** [comment]
Thanks LloydPickering for your response .
But still problem is pending . Hope so , Martin will be suggest any solution regarding this problem.

**Comment by martin1cerny** [comment]
Hi dhundaleamol, 

First of all I'd suggest to use Nuget or Myget to reference necessary libraries into your MVC project rather than converting WeXplorer into MVC application. It is intended only to be a *development and testing environment*. Supposed scenario is to create standard MVC application and to add Nuget package. WeXplorer is under development now so it is only available from [myget](https://www.myget.org/) package [repository](https://www.myget.org/F/xbimtest).

However, you can of course just grub the files from the *Build* folder. In any case make sure your JSON file exists and is available (try to enter the URL where it should exist into your browser). Make sure your IIS is set up to serve JSON files as a static content if you use it that way. If it exists copy the JSON string into your clipboard and try to parse it into a javascript object in your browser console 

    var cobie = JSON.parse('your_data_surrounded_by_quotes');

If this fails your JSON file is not valid. In all browsers except for IE parsing happens within AJAX call and it fails if JSON file is not well formed (like if you didn't close the stream and it is incomplete of if you cut and paste from the debug console and it contains invalid characters or syntax).

If nothing helps let me know please.

Regards, 

Martin

**Comment by LloydPickering** [comment]
Can we mark this issue as closed?

**Comment by dhundaleamol** [comment]
Yes ,You can .Lioyd


-- 
Thanks & Regards,
  Amol Dhundale
