### ISSUE TITLE
Develop branch how to package with webpack

### ISSUE THREAD

**Issue by jkfhto** [xBimTeam/XbimWebUI#204]
Using the latest webpack package will report an error, how can I solve it?

**Comment by martin1cerny** [comment]
Build dependencies are broken in the current version. I work on refactoring towards pure Webpack+Typescript project without any C# code. For now, you need to open a Task Runner extension, run develop and production build and than run TypescriptBundler utility. I know this is all very messy and needs refactoring as I noted above.

**Comment by SBRK** [comment]
Any ETA on when we can use and build the develop branch correctly ? I would like to add some things, like support for devices without floating point texture support or improvement on camera interactions.

Doing them on master branch seems like a waste of time because of the develop branch that is more advanced, but building develop branch seems too broken to work on that branch...

**Comment by SBRK** [comment]
I got it to build by making my own npm script. But performance seems bad compared to the master branch (45FPS vs 60FPS with the same file)

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer).  It uses webpack and TS. It is no longer a Visual Studio project, but a standard JS/TS library.
