### ISSUE TITLE
Jittering of wexbim model between IfcSpaces, IfcSlabs and IfcWalls

### ISSUE THREAD

**Issue by Truning** [xBimTeam/XbimWebUI#219]
I experience ugly jittering of some IfcSpaces, IfcSlabs and IfcWalls when viewing the wexbim file (see image below). It is even worse while moving the camera around. I observed that the jittering almost entirely goes away when zoomed further in.

![image](https://user-images.githubusercontent.com/42533827/50292662-fb925e80-0471-11e9-9202-8d6d867c0ccc.png)

I know that this happens because of the surfaces of an IfcSpace being exactly on the IfcSlabs, so when rendering them it is not clear which object should be rendered on top of the other. But is there a way to fix this? For example when creating the wexbim file is there a way to shrink the IfcSpaces just a tiny bit, so that their coordinates don't correspond to the ones of the walls and floors anymore? Or is there a way to tell the xViewer to always render the IfcSpaces on top the of IfcSlabs?

Thank you in advance for any help!

**Comment by martin1cerny** [comment]
This effect is caused by the interference between spaces and other elements. Two planes occupy exactly the same space so GPU can't distinguish between them and the only difference is a floating point precision of GPU operations. When spaces are semitransparent in their default appearance we offset them slightly to avoid this effect. But your spares seem to be non-transparent so even we can't know what is the preferred thing to show. You should either make your spaces semitransparent before you process the geometry or you have to come up with some other logic.

**Comment by Truning** [comment]
Hi Martin! Thank you for the quick answer as always!
How can I make the spaces semi-transparent? You wrote I should do this before processing the geometry, so do you mean in the process of creating the .wexbim file? I could't find anything in the "SaveAsWexbim" method that would suggest making some products semi-transparent.

**Comment by martin1cerny** [comment]
You would have to change it in the actual IFC model. But thinking about it, it might be better to apply the offset for spaces by default in the viewer.

**Comment by Truning** [comment]
Unfortunately changing the IFC is not an option for me. Unless there is a way to do it automatically with the XbimGeometry package?

> But thinking about it, it might be better to apply the offset for spaces by default in the viewer.

Any tips on how I would be able to do this?

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). It applies small offset to all semi-transparent object to avoid this unwanted visual effect.
