### ISSUE TITLE
How can I change scroll and pan speed ? 

### ISSUE THREAD

**Issue by OmarKhairyHosny** [xBimTeam/XbimWebUI#257]

**Comment by heltonmatiazi** [comment]
In your 'viewer' file there's a switch statement with a structure like this: 
 case 'pan':
                        _this.navigate('pan', deltaX, deltaY);

shortly after, there's an if statement like this:
if (button === 'middle' || button === 'right'){
 this.navigate('pan', deltaX, deltaY);
}

You can change the deltaX and Y in these cases to have the speed that you like.
I'm using it like this:
this.navigate('pan', (deltaX/9), (deltaY/9))

...and with this, the model follows the mouse while in 'pan' mode instead of moving out of the screen instantly.

**Comment by martin1cerny** [comment]
We have published new version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). This new and much improved version has much better navigation. It respects actual 3D point of interaction both for zoom and for pan.
