### ISSUE TITLE
Zoom in Orthographic is not working

### ISSUE THREAD

**Issue by OmarKhairyHosny** [xBimTeam/XbimWebUI#261]
Zoom in Orthographic is not working, any help in that ? Thanks.

**Comment by laarmen** [comment]
The zoom word is a misnomer, as the action here is to move the camera
forward, instead of changing the camera settings. In perspective mode the
result is similar (but not the exact same) to reducing the FoV, however in
orthograpic projection moving the camera forward will only change where the
near and far clip planes are, without changing the on-screen size of the
objects.

If you want to implement a camera zoom, in perspective camera you'll need
to reduce its field of view, and in orthographic camera you would reduce
top, left, bottom and right.

**Comment by OmarKhairyHosny** [comment]
How can I implement this ?

**Comment by martin1cerny** [comment]
Implemented in the current release.
