### ISSUE TITLE
Can we retrieve a data(propertes & attributes) from xbim file instead of json file 

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#28]
Is it possible,to retrieve a data of object .ie properties and attributes (like a Area,volume ,height,width).
I have seen in XbimWebUI  project .There is properties and attributes window of object ,which is showed by using json file..

But ,Is it possible to retrieve that same data by using .xbim file.

**Comment by andyward** [comment]
Sure. All the data is in the Xbim file. Xbim files are a binary version of the IFC file optimized for reading and writing (typically with Linq). The Json data you've seen is generated by the Xbim.Exchanger library using the Xbim Essentials core in order to create a single json file for the web.  

If you want to learn how to interrogate the model for properties perhaps the best place to start is by getting the code for [XbimXplorer](http://github.com/xBimTeam/XbimWindowsUI) and sticking some breakpoints on the code. E.g. take a look at https://github.com/xBimTeam/XbimWindowsUI/blob/master/Xbim.Presentation/IfcMetaDataControl.xaml.cs#L90
 
(which is the code that populates the values in the Properties tabs)

![image](https://cloud.githubusercontent.com/assets/923699/9067282/60b6d78e-3ad4-11e5-83cc-d384412b2a32.png)

The same code is applicable to the web - although the architecture will obviously be different.
