### ISSUE TITLE
Possible multiple models loading

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#29]
Hello,
I wojld like to ask if is it possible to load more than one model and get all built to one to be display with the framework.

Thanks

**Comment by LloydPickering** [comment]
It's certainly possible on the C# code side. I'm not sure what's been put into the web frontend/API. Martin will know.

**Comment by andyward** [comment]
You can federate the geometry of multiple models pretty trivially in the WebUI. Just load multiple wexbim files into the JS xViewer. See https://github.com/andyward/XbimWebDemo/ for a basic example. Federating the data semantically may be a bit more work depending on what you want to do (i.e. if you want to consolidate the data in anyway)

You'd have to check whether the JS framework handles segmenting the entity labels correctly to avoid duplication (since entity labels could be the same across models.)

**Comment by johnBim** [comment]
Hello Andy,
Thanks a lot, I will try that

regards
