### ISSUE TITLE
Problem loading federated files

### ISSUE THREAD

**Issue by jefersonpa** [xBimTeam/XbimWebUI#292]
Hi, i have a problem with 2 models, when adding both to the same project it only displays 1.

For example, in XbimXplorer the files look like this:
![image](https://user-images.githubusercontent.com/52458723/88854268-6582f600-d1c7-11ea-90b7-88dd2c98d6cb.png)

But, it looks like this when opening in XbimWebUI:
![image](https://user-images.githubusercontent.com/52458723/88854548-d2968b80-d1c7-11ea-8eb1-ad505a5de2b8.png)

Does anyone know how I can solve this?
Thanks in advance

#### Minimal code (or steps) to reproduce the issue:
```js
viewer.load("tests/data/R01.wexbim");
viewer.load("tests/data/R02.wexbim");
```

#### Minimal file to reproduce the issue:
[IFC and WEXBIM files](https://github.com/xBimTeam/XbimWebUI/files/4997450/IFC.%2B.WEXBIM.zip)

**Comment by pml1711** [comment]
@jefersonpa did you find a way to "fix" this? I am facing a similar problem. In my case, the Revit files and the IFCs exported from the files are processed/rendered in the same way in Solibri and Xbim Explorer. But in XbimWebUI one overlaps the other, it is like if they had the same origin point. And I have no idea if it is a bug, it seems like though because every other IFC viewer renders "correctly" 

Revit 2021
![image](https://user-images.githubusercontent.com/77131323/103960588-3fc42a80-5131-11eb-9ca1-6ad36accab2b.png)

XbimExplorer
![image](https://user-images.githubusercontent.com/77131323/103960614-52d6fa80-5131-11eb-916a-a2d77cf83c51.png)

Solibri
![image](https://user-images.githubusercontent.com/77131323/103960657-68e4bb00-5131-11eb-8f65-3508ba72522f.png)

XbimWebUI
![image](https://user-images.githubusercontent.com/77131323/103960690-81ed6c00-5131-11eb-8d72-7eb3bff15c1b.png)


IFC files --> 
[ifcfiles.zip](https://github.com/xBimTeam/XbimWebUI/files/5784678/ifcfiles.zip)

**Comment by martin1cerny** [comment]
There is an optional argument in when creating the wexBIM file. By default it doesn't consider large site displacement to keep coordinates smaller for better rendering quality. But you can also supply your own origin (same for both files) which will make them aligned.
