### ISSUE TITLE
How to show components' information on the websites?

### ISSUE THREAD

**Issue by outsidewindow** [xBimTeam/XbimWebUI#350]
Hi,i am a student and recently i am learning about xbim,but i meet some problems .So i'm waiting for your kindly help,Here is my question .If i want to show components' (material) information(json file exported from revit) on the websites,like the  xbim-meets-angular projects you before upload to the github  ,how can i do? And i want to know is there any  material information in the wexbim file?Wish your reply,thanks!

**Comment by GeorgDangl** [comment]
Hey @outsidewindow, I thought I'd reply since you mentioned `xbim-meets-angular`😀

The `*.wexbim` files don't contain any material information - they're just a binary format with geometry data that is displayed in the viewer, very simply said. They have one reference information for objects, the entity id (or entity label), which is the number you see at the start for every entity in IFC files.

To be able to show material data and other information, you need to not only convert the IFC to wexbim, but you also need to extract the data you want from it. Typically, you'd often export some base data like properties, types, spatial structure and link this to the model via their entity id. But that's all up to you😀

On the `xbim-meets-angular` page, there's the model browser from this repository. I think that's more an example than a finished component you'd want to integrate, but you can inspect the code to find out more about it.

**Comment by outsidewindow** [comment]
Hi@GeorgDangl ,I am very grateful to receive your reply!As a  rookie,I try my best to  read the code from the model-browser.component.ts,but i can't find these two api:'@dangl/xbim-viewer and @dangl/xbim-browser,and  i want to know about the LakesideRestaurant.json file which contains material data and other information ,how can i export this file from revit,perhaps i can use  xbim plug-in to achieve this function?Hope to get your reply，best wishes!

**Comment by GeorgDangl** [comment]
Hey @outsidewindow, the packages you're referencing are rather old, I pushed them at a time where there were no officla xBim packages available. So I'd advise to use the official builds.

As for the `LakesideRestaurant.json`, I believe that's a demo file that was (probably is?) distributed somewhere by xBim themselves. As far as I know, it's a Cobie export from an IFC model, and is used as a demo for the xBim Browser.

I don't know if it's possible to export xBim data directly from Revit via a plugin, but generally you would go the route of first exporting to IFC, and then taking this IFC file and producing two outputs:
1) A `wexbim` file with the geometry package, for rendering the file
2) A custom `json` file (this format is totally up to you), where you just use the xBim libraries to extract whatever data you want from a given IFC file and then serialize this to e.g. JSON

The second part is really free - xBim gives you the possibility to extract any data you want, but it's up to you what data you need, how to export it and finally to create a custom way to visualize the data.

**Comment by outsidewindow** [comment]
Hi@GeorgDangl ,thank you very much ,i will try again to achieve the goal .Thank you again！
