### ISSUE TITLE
Apply style to all elements in viewer

### ISSUE THREAD

**Issue by bcanteneurEiffage** [xBimTeam/XbimWebUI#354]
Hi everyone and thanks for your help, here is my issue :

#### Expected behavior:
I would like to apply the same style to all elements in my viewer (containing multiple models) before showing some of them with specific colours.
I am struggling in the part where I apply the same style to all objects.

#### Actual behavior or exception details:
Here is the error I get with each versions of the code I tested :
```
Uncaught TypeError: t.forEach is not a function
    at t.getMaps (model-handle.ts:976)
    at t.setStyle (model-handle.ts:945)
    at viewer.ts:807
    at viewer.ts:673
    at Array.forEach (<anonymous>)
    at t.forHandleOrAll (viewer.ts:671)
    at t.setStyle (viewer.ts:806)
    at showModelState (Model:645)
    at HTMLInputElement.onclick (Model:404)
t.getMaps @ model-handle.ts:976
t.setStyle @ model-handle.ts:945
(anonymous) @ viewer.ts:807
(anonymous) @ viewer.ts:673
t.forHandleOrAll @ viewer.ts:671
t.setStyle @ viewer.ts:806
showModelState @ Model:645
onclick @ Model:404
```

#### Version of the xBIM Viewer:
last one on npm

#### Minimal code (or steps) to reproduce the issue:
```
for (let productType in ProductType) {
    viewer.setStyle(0, productType);
}
```

I also tried
```
for (let productType in ProductType) {
    viewer.setStyle(0, ProductType[productType]);
}
```

**Comment by jomijomi** [comment]
Hi, I think the easiest path here is to use the hierarchical nature of IFC object types. For instance, when I want to isolate a certain type, let’s say walls, I do:
```
viewer.setState(State.HIDDEN, 20); //IfcProduct
viewer.setState(State.UNDEFINED, 452); //IfcWall
```
In the above code I first set all IfcProducts to hidden (which basically means all objects because IfcProduct is the parent class). I then set only walls as visible (i.e. undefined). Note: above code is for state, but the same approach should work for styles (I think...)

/Mikael
