### ISSUE TITLE
Ifc label in COBie Excel output (Component Sheet)

### ISSUE THREAD

**Issue by redgeway-edocs** [xBimTeam/XbimWebUI#36]
Moved from: https://github.com/xBimTeam/XbimWindowsUI/issues/10

When using the Xbim web viewer the COBie data is associated by the ifc label id and in the Xbim Windows viewer the COBie Excel output that is produced uses the ifc GUID,which one should be used as there seems to be no apparent link between the two?

**Comment by andyward** [comment]
There are two separate COBie implementations in the Xbim toolkit - both found in the Xbim.Exchange package/repo

**Xbim.Cobie** creates COBie data from IFC according to the [COBie Responsibility Matrix](http://projects.buildingsmartalliance.org/files/?artifact_id=4093). This is typically the 19 sheet spreadsheet you'll see and the UK BIM standard http://www.bimtaskgroup.org/cobie-uk-2012/

**XBim.CobieLite*** creates [COBieLite schema] (http://www.nibs.org/?page=bsa_cobielite) which is simpler for programatically manipulate. The COBieLite implementation is a bit more customisable than the original Xbim.COBie implementation.

While the two formats are interoperable (they have the same fields & entities) there may be discrepancies between the two implementations. In the case of the identifier field, COBieLite library has an option in [COBieLiteHelper.cs](https://github.com/xBimTeam/XbimExchange/blob/master/Xbim.COBieLite/COBieLiteHelper.cs#L835) to choose between the Entity Label and the Guid. 

```csharp
        public string ExternalEntityIdentity(IfcRoot ifcObject)
        {
            switch (EntityIdentifierMode)
            {
                case EntityIdentifierMode.IfcEntityLabels:
                    return ifcObject.EntityLabel.ToString(CultureInfo.InvariantCulture);
                case EntityIdentifierMode.GloballyUniqueIds:
                    return ifcObject.GlobalId;
                default:
                    return null;
            }          
        }
```

So you *can* switch COBieLite to output Guids but can't change COBie to use Entity Labels

I suspect COBieLite implementation allows Entity Labels to simplify the mapping process between IFC and COBie. @martin1cerny may provide some more input. 

While you could back-port this switch into the XbimCOBie mapping implementation I'd caution against it as you'd be going against the COBie mapping rules - and because of the label is not stable.

In terms of fixing your issue, it depends a lot on what you're trying to achieve and the wider use cases (i.e. What does the user want to see/do? Will it be the model, or COBie that is the starting point for interaction? or Both? is the data presented readonly? Are you federating models?) 

Ultimately you're going to have to create some mapping of IfcLabel[+Model] <-> IfcGuid. You could then use that map client side, or augment your COBie (Json) model with the mapped values before it goes over the wire.

I suppose an alternative would be to extend the wexbim to hold the ifcGuid, but that's going to be a breaking change and increase the payload significantly

**Comment by martin1cerny** [comment]
Thanks @andyward . COBie specification doesn't impose any kind of external identifier. However, IFC GUID is the most universal and should allow for versioning, model comparison, external references and other. But if you intend to use COBie as a semantic data together with our WebUI you will need entity labels. 

There is a simple constraint that id has to be an integer in order to implement any picking operations in WebGL. This is why we use this. It is also much simpler to use integer ID in the wexBIM file format and should be better for performance of any search as it should be easier to search for a number than for a string (which happens with any change in style like highlighting, xray mode or anything else).

**Comment by redgeway-edocs** [comment]
Thanks for the replies and information. We understand why the Xbim Web viewer requires the element id to be an integer however,  to allow us to attach the data to the geometry we've appended the entity label to the COBie component sheet when it's generated. We are then using the COBie sheet and importing into our CDE, this allows us to hook up the geometry with the data.
