### ISSUE TITLE
GetProductType function error

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#37]
Hello,
I got an error while trying to hide by type. Basically the issue is related to the getProductType function which throws the following error. could you please help?

![getproducttypeissue](https://cloud.githubusercontent.com/assets/12897988/9921150/e8a6cb90-5cda-11e5-9fbd-44932d797b9f.PNG)

Thanks

**Comment by mbacon-edocs** [comment]
I had this issue as well, for me it was because the map variable it's trying to use is an object, not an array. To bypass this I've currently put this line in (though it's not very defensive):

`if(map instanceof Array === false) return map[prodId] ? map[prodId].type : null;`

Making the `getProductType` function this:

```
xViewer.prototype.getProductType = function (prodId) {
    for (var i in this._handles) {
        var map = this._handles[i]._model.productMap;
        if(map instanceof Array === false) return map[prodId] ? map[prodId].type : null;
        var prod = map.filter(function (e) { return e.productID == prodId }).pop();
        if (prod) return prod.type;
        else return null;
    }
};
```

Hope this helps, maybe the core can introduce a more defensive fix to this problem

**Comment by johnBim** [comment]
Hello,
I will try this one
Thanks

**Comment by martin1cerny** [comment]
Hello @johnBim ,
thanks for spotting out this bug. It used to be an array but I've changed it to be an object for the sake of performance and this one is a residuum. The right code is enough to be

```js
xViewer.prototype.getProductType = function (prodId) {
    for (var i in this._handles) {
        var map = this._handles[i].getProductMap(prodId);
        if (map) return map.type;
        return null;
    }
};
```

You can get it from the latest source of development branch.

**Comment by johnBim** [comment]
Hello Martin,
thanks I will use it.

Regards
