### ISSUE TITLE
Coloring Element

### ISSUE THREAD

**Issue by untecnologo** [xBimTeam/XbimWebUI#437]
Hello, Thank you for taking your time. 

I am trying to color a surface after being clicked.

![image](https://github.com/xBimTeam/XbimWebUI/assets/37328540/156060e6-0362-44d3-99ce-59c1b254cd92)

Is there any tutorial or example, I was checking but the old documents are not available anymore in the old answers

**Comment by andyward** [comment]
The latest docs are at https://docs.xbim.net/XbimWebUI/

I think the issue with your original code in the onClick is that the 2nd parameter expects an array of ids.

See https://docs.xbim.net/XbimWebUI/classes/Viewer.html#setStyle

It should be:

```
wexBimViewer.setStyle(3, [arg.id], arg.model);
```

When you pass in a number (rather than array) it's assumed to be the [ProductType](https://docs.xbim.net/XbimWebUI/enums/ProductType.html)
