### ISSUE TITLE
Hide some elements while zooming / panning to improve performance?

### ISSUE THREAD

**Issue by AlainBolduc** [xBimTeam/XbimWebUI#50]
Hello,

If I load several IFC files (or a large one), the viewer  displays all the items contained within the file, including less important details such as chairs, tables, etc... (which is expected, of course!)

It could be interesting to have a mode where, while zooming / panning, only a subset of the elements are rendered during these operations. Once the user stops interacting with the model, is gets 100% rendered.

Is this something you plan to develop? or maybe it is already supported? 

Thanks!

**Comment by martin1cerny** [comment]
Hi Alain,

we did talk about something in these lines but it is not implemented yet and we don't have a plan for doing this in the close future. It wouldn't be hard to do but we have other development priorities at the moment (like IFC4 full support).

Martin

**Comment by AlainBolduc** [comment]
Ok, thank you very much.

If I decide to implement this myself, do you have some hints to give that I should follow in order to make it efficiently?

Also, can you give me some insight on what is missing for ifc 4 support?

Thanks!

Alain

**Comment by martin1cerny** [comment]
To make it efficient you should do it in vertex shader. You would have to create new vertex shader attribute and buffer in new typed array which would represent type of the product being rendered. This information in not being passed to vertex shader now because it is not necessary for any current functionality. But the information [is part of the WexBIM file.](https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/xbim-model-geometry.debug.js#L113).  Then you would have to create new uniform which would indicate to shader if to leave specified vertices out for this pass. Than you would add a condition in the vertex shader which would decide based on the flag and type of the product whether to render it or not. If not you would pass a varying attribute to fragment shader which would than discard all respective fragments.

Current design doesn't allow to leave some parts out of rendering pipeline completely. We based the implementation on assumption that we gain most performance if we pass all the data onto GPU once and render the static scene from this data all the time afterwards.

As for IFC4 support I've created full IFC4 implementation which works. It means we can read/write/modify any IFC4 file already. This is not public release yet but you can find it under development branch should you wish to have a look. We currently work on upgrade of geometry engine to IFC4 with backwards read-only compatibility for IFC2x3. It will still be possible to write/modify IFC2x3 with full extent but that must be version specific code whereas reading of the data will be unified. We are almost finished with this one. Once done we can also generate wexBIM files for IFC4 and will continue to upgrade other parts of the xBIM Toolkit in the same way.
