### ISSUE TITLE
I already have a webgl viewer and i want xbimwebui to read properties and geometry data

### ISSUE THREAD

**Issue by IFChaos** [xBimTeam/XbimWebUI#56]
Hello,

I had made a WEBGL viewer and i also programmed a method to open and save files in JS. I only want to know if it is possible to use XBimWEBUI to obtain only geometry data (nodes coordinates, triangles/faces and axisplacement3D) and properties of each element. But i have no idea how to do it.

Is it possible? Maybe loading some JS libraries i can do it?

**Comment by martin1cerny** [comment]
Hi @IFChaos , it is possible to use [part](https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/xbim-model-geometry.debug.js) of XbimWebUI project to only parse the binary wexBIM file to get the geometry (indices, vertices and transformations of mapped items). This file doesn't contain any properties apart from the entity id and product type. If you use [XbimExchange](https://github.com/xBimTeam/XbimExchange) to convert the data you can also extract properties and other semantic data from IFC in form of COBie data serialized as JSON. However, this tends to be very large for a large models and so to make your solution scalable I'd recommend using web service to only fetch the data you need for a user rather than full model. It is very easy to use xBIM to build such a service as it features indexed DB storage (*.xbim file) with instant access to any part of the model.
