### ISSUE TITLE
Wexbim image not loading after page refresh.

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#61]
Initially the wexbim image (BIM model) loads ..but after refreshing the page (F5) the BIM model does'nt load anymore. The only option is to close and reopen the browser and again reload the page to get the model. Issue exists for all major browsers (firefox,chrome).

If the model is kept open in firefox for over 30 mins .. firefox crashes.

How to fix the above mentioned issues?? (The file size of the BIM model is 910 mb).

**Comment by BIMDevelopement** [comment]
I have tested latest xbimWebUI source also. But there is also same problem occur. First time model is loaded , but after refreshing , it is not loaded or it takes more time also. Some time , browser is crashed.

**Comment by martin1cerny** [comment]
Hi @BIMDevelopement ,

As web is designed as a stateless environment xViewer doesn't implement anything that would maintain the state across page reload. It is purely **your responsibility** to reload the model if necessary. It can also take more time because browser might assume you want to clear the cache for the page and will reload more than before. 

If your IFC file is almost 1GB I assume that resulting wexBIM file might be about **100MB**. Note this is fairly compressed data stream of triangulated geometry. However, any browser is limited sandboxed environment even that WebGL is HW accelerated. xViewer doesn't do anything unless user or API interact with the viewer so make sure you don't do anything in `setInterval()` or similar which would force it to render all the time. Also consider if file of this size is actually usable over network. You might consider to advise your BIM model authors to split the model into smaller sensible chunks or to use lower LOD.

I'm sure that as a developer you appreciate the importance of relevant error reports. If *"something sometimes crashes with some error"* it isn't possible to find actual problem.

**Comment by BIMDevelopement** [comment]
How much maximum file size can handled a browser without browser crashed?

**Comment by martin1cerny** [comment]
It depends on your CPU, GPU and WebGL implementation of your browser. 

Browser shouldn't crash at all. But I saw WebGL application to crash high-spec PC back in 2011 when WebGL started to be supported so I know it is possible.
