### ISSUE TITLE
Ensure visibility of all highlighted items

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#68]
Hello,
I would like to know if it will be possible to simulate "ensure visibility of all highlighted items"?
e.g. Zoom to all  highlighted items.

Thanks

**Comment by martin1cerny** [comment]
It is easy to do. Just have a look on [setCameraTarget()](https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/xbim-viewer.debug.js#L492)  and [zoomTo()](https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/xbim-viewer.debug.js#L1084) functions. You will just need to change it so that it creates aggregated bounding box of all selected elements to compute origin and origin, distance of the view.

**Comment by johnBim** [comment]
Thank you I will have a look
