### ISSUE TITLE
Necessity of IfcSpace

### ISSUE THREAD

**Issue by swy0930** [xBimTeam/XbimWebUI#79]
Hi Martin,

I am trying to split a wexbim file by its floors and spaces. I am wondering whether it is standard to have spaces in a model or it depends on different designers or companies, since I found some models didn't have any space in any floor. But I do believe there could be some nonstandard examples online.

Thank you very much!
Ivy

**Comment by martin1cerny** [comment]
Hi @swy0930 ,

it is common that models contain spaces but it is not a standard unless it is a requirement from client or somebody else in the process. IFC provides rich data infrastructure how to model this kind of spatial relation as a semantic data but it doesn't have to be used. I've seen model while ago where many doors were assigned to three or four spaces instead of just 2. It is common for models from Revit for example that spaces are 4m height which might not be attached to any sensible top level (like ceiling or bottom plane of the upper floor slab) and might easily create overlapping spaces. Plus there are mechanical and architectural spaces which are not related. To round it up it is not straightforward to split the model spatially by spaces reliably.

**Comment by swy0930** [comment]
Thank you, Martin. It seems write an application depends on space is not a good idea.
