### ISSUE TITLE
"Moved From XBimExchange" Converting to wexbim - Removing elements from a .wexbim File to improve Performance

### ISSUE THREAD

**Issue by dazmahal** [xBimTeam/XbimWebUI#80]
Hi folks
Query related to Converting to wexbim -
Our developer has worked on .json file removing any unwanted elements, and after the web optimization got the payload down from 70mb to < 5mb.
Can we undergo a similar process with the .wexbim file - What type of elements can be removed without effecting its integrity?

Thanks
Darren

**Comment by martin1cerny** [comment]
Hi Darren,

this is more difficult as it is hard to tell what is not important. WexBIM file needs to be written begin-to-end so that it contains final counts of basic elements to avoid memory reallocations in a browser. So it is rather advisable to split the model before the generation and only generate the model you need or generate information sets which can be loaded separately (xViewer can already load multiple wexBIM files). We've been thinking about this for a while but didn't decide for the best strategy yet.

**Comment by martin1cerny** [comment]
There is a new function in `IfcStore` in `develop` branch which you can use to create wexBIM file containing only specific products. It is alpha implementation but is tested to work well if you save all elements of the same type (say all doors, all windows etc.)
