### ISSUE TITLE
Unload method on xviewer object

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#81]
Please, could you provide  unload method on xviewer object, which can be used to unload a loaded model. This method should completely free the memory. Useful if user loads multiple model and want to unload some of them.

Thanks

**Comment by AlainBolduc** [comment]
I agree on this one. We managed to find a way of completely hide a model from the viewer, but it does not unload the model itself..

It would be a major improvement for us too.

**Comment by martin1cerny** [comment]
I agree this is a useful feature to have and will put it on the wish list for the viewer. However, our development resources are fully focused on IFC4 support at the moment. This involves refactoring of all packages which used to use IFC2x3 only. xViewer is platform independent except of an enumeration of types so it is not a part of this effort.

**Comment by martin1cerny** [comment]
Suggested method for now is to remove canvas from HTML tree and to create brand new one.

**Comment by AlainBolduc** [comment]
This works well when only one model is loaded. however we are loading several (potentially big) models in the same canvas.

This suggested method cannot be used in our case and a true unload solution would be better...

**Comment by johnfoundations** [comment]
I agree with Alain. But ... the scale is Wrong ... single BIG model also has this problem.This is also highly related to the "joystick" discussion thread. Do you really want to partition the client side in-memory image, or do you want these controls on the server side?

For example, I just added an embedded "token" based  simple xViewer to my  application.
A more promising approach is "tiled canvas" where a partial model can be uploaded. My model data loads via PHP from a DB, not a file, so it can be filtered. Requirement for Unload() is inherent.

 I have very limited test resources, but I could do Unload() code and send to a Contrib folder. I can also investigate getting Northumbria China involved if this would be helpful. Apparently Northumbria China is looking for BIM research projects.

**Comment by johnfoundations** [comment]
Attached is a model unload that works for me.

[unload.zip](https://github.com/xBimTeam/XbimWebUI/files/289910/unload.zip)

**Comment by martin1cerny** [comment]
Hi @johnfoundations , nice candidate for a **pull request**. It would just be more clear to add "Id" property to model handle and to remove your helper indices. That would also make your `delete` work. It can't work now because model handle is still referenced in `viewer._handles`.

**Comment by johnfoundations** [comment]
Hi. Thanx for responding so quickly.  I have no idea what a pull request is ... branch on Github?
Doesn't the splice get the handle (line 569) out of the viewer._handles so that delete works? I found this example on the internet as how to delete from arbitrary entry of push / pop array.
 If a controlling application is going to unload() given an ID, it should also load() with an ID, and the library layers should propagate this ID. If it was my choice, mload(id, binaryReader) would be the constructor, not mload(id, file handle).
Now ... there is more ... if I am reading this code correctly. It appears that geometry.load()/parse() does a purely sequential pass, once, through the array buffer.  PLEASE CONFIRM!!!!!!!!!!
If so, and binaryReader is external, there are many things that can be done, such as compressed chunk encoding.

**Comment by martin1cerny** [comment]
[Pull request](https://help.github.com/articles/using-pull-requests/) is a way to contribute to xBIM project on GitHub. See the documentation [here](https://help.github.com/articles/creating-a-pull-request/) on how to create one.

You are right about removing the handle from array. I only went quickly through the code and missed the line 569. It should work as it is.

Your current implementation is neither `mload(id, binaryReader) ` nor `mload(id, file handle)`. It is `mload(id, model)` where model is either URL to wexBIM file or Blob or File representing wexBIM file binary data. That is effectively what you want because binary reader is then just used under the hood. 

`geometry.load()` -> `parse()` is not necessarily sequential. If you pass in model as a string pointing to wexBIM file on a server it uses asynchronous AJAX to fetch the data. If you pass in a model as a `Blob` or `File` it depends if loading of the data (reading from the file) is implemented as a synchronous or asynchronous operation in the browser. But the API suggests it is asynchronous (using [onload event](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/onload)).

**Comment by johnfoundations** [comment]
Never mind. BinaryReader() is loaded from html file. It is just an API. Sometimes I wonder about our little brains.
I suspect that the barrier to model scalability is the ID from (x,y) on mouse click within viewer.
On some thread someone was complaining that 900MB IFC to Wexbim conversion takes too long.

**Comment by martin1cerny** [comment]
I don't think that getting ID from mouse position is the barrier.

As for a conversion, it might take some time to convert IFC to wexBIM. But bare in mind that 900MB model is quite large file where it takes time to do anything with it. I spoke to a colleague the other day and he was complaining about performance of the xBIM web viewer with the wexBIM file coming from 500MB IFC file. It turned out that it took several hours on a high-spec PC to actually assemble and export the file. So it is not a surprise that rendering in web browser is not perfectly responsible. Yes, web is a constrained environment even with HW acceleration.

**Comment by johnfoundations** [comment]
For my BIM file system, a construction company suggested 10-20 tracked model versions, and hundreds of informal working versions over time. This suggests to me that lightweight tools are required, making a 200MB+ IFC flat file a non-starter.

I am unifying BIM model approval / BIM delivery scheduling, 3d browsing, and Windows Drive access to data, to eliminate excess copying, because people complain that Revit Design Review to BIM information exchange process is a make work project, and a distributed team never all has the same copy of data, because they are constantly doing export / import.

**Comment by martin1cerny** [comment]
Implemented.
