### ISSUE TITLE
How to implement walk through functionality ?

### ISSUE THREAD

**Issue by dhundaleamol** [xBimTeam/XbimWebUI#9]
Hello ,

I stuck to implement this functionality in BIM viewer . Can you please help me to get any clue to develop WALK through functionality in BIM .

**Comment by edocs** [comment]
Hi @dhundaleamol,

We have forked this project and have created the functionality I believe you're after here: https://github.com/Edocuments/XbimWebUI

The implementation still requires a bit of tweaking, namely fine tweaking values so that navigation is comfortable at different zoom levels, but let us know what you think.

**Comment by edocs** [comment]
As mentioned on another issue, I forgot to mention how to actually use the new navigation mode:

You will need to set the navigationMode property to "fly" on the xViewer instance. Example code below:

```javascript
var viewer = new xViewer(viewerId);
viewer.set('navigationMode', 'fly');
```

**Comment by dhundaleamol** [comment]
Hello,
 I have tried  this viewer.set('navigationMode', 'fly'); But Its not working . I didn't get any proper solution. 
xbim-viewer.debug.js mention the functionality for PAN .as follows
function navigate(){
 switch (type) {
  case 'pan':
                mat4.translate(transform, transform, [deltaX * distance / 150, 0, 0]);
                mat4.translate(transform, transform, [0, (-1.0 * deltaY) * distance / 150, 0]);
                break;
                 }
}

Is it something like for Walk option?

**Comment by edocs** [comment]
The fly navigation mode should be using a navigation type of 'spin' for mouse movements - you should be able to see `case 'spin':` on line 870 and 1091.

If fly is working you should be able to navigate the model using arrow keys (or WASD) to move around and just move the mouse to look around.

**Comment by dhundaleamol** [comment]
Thanx for replied.

I have checked fly functionality .But I am not accepting that one. I want to walk functionality as,
1) I hold mouse left-click and go with Front direction --So it moves to Front direction of diagram
2) I hold mouse left-click and go with Back direction --So it moves a Back direction of diagram
3) I hold mouse left-click and go with Left direction --So it moves a left direction of diagram
3) I hold mouse left-click and go with Right direction --So it moves a Right direction of diagram

**Comment by edocs** [comment]
Sorry but I'm not sure I understand. Do you mean that you want to hold down the left mouse button, and only pan or zoom depending on whether you're moving side-to-side or forward and backward? (As if you're sliding a picture around the surface of a table)

**Comment by dhundaleamol** [comment]
Yes , I want exactly what you understood . 
I need a PAN option for left and right direction .And Zoom In and zoom out for front and back resp.

**Comment by edocs** [comment]
In which case our modifications to the source code won't be of much use apart from the pan and zoom speed configurations, so you may want to revert back to the original source.

A very quick untested hack below (based around the line containing `if (button == 'middle') {` in the `handleMouseMove` function within `xViewer.prototype._initMouseEvents`:

```javascript
if (button == 'left') {
	/*
	switch (viewer.navigationMode) {
		case 'free-orbit':
			navigate('free-orbit', deltaX, deltaY);
			break;

		case 'fixed-orbit':
		case 'orbit':
			navigate('orbit', deltaX, deltaY);
			break;

		case 'pan':
			navigate('pan', deltaX, deltaY);
			break;

		case 'zoom':
			navigate('zoom', deltaX, deltaY);
			break;

		default:
			break;

	}
	*/
	navigate('pan', deltaX, 0);
	navigate('zoom', 0, deltaY);
}
if (button == 'middle') {
	//navigate('pan', deltaX, deltaY);
}
```

The original code has just been commented

**Comment by martin1cerny** [comment]
Hi @edocs ,

nice to see you extending XbimWebUI functionality. Walk through navigation has been on my development wish list already along with other features. I'll definitely make navigation more configurable, exposing 'navigate()' function for the start so that other navigation models can be implemented as the plugins rather than hacks. 

Do you have any plan on pushing your enhancements back to our repository?

Regards

Martin

**Comment by edocs** [comment]
Hi @martin1cerny,

Ah good, that certainly sounds like a good way to go. Our plan was certainly to see if you wanted to merge our code, but as it currently stands the implementation isn't quite solid enough. I'm just preparing a demo of how it currently works if you'd like to see it?

**Comment by edocs** [comment]
Hi @martin1cerny,

As mentioned above, you can see a demo of our 'fly' navigation mode [here](http://xbimviewer.azurewebsites.net/browser.html?model=lakeside) - as our current integration of your viewer is only part of a larger website (rather than the whole page as with this demo), we've had to change how 'greedy' the event handling is - you therefore need to click on the canvas area in order to gain control. This sort of thing could be easily tuned by a config property of course.

Speed and handling issues are yet to be properly addressed and may require tuning on-the-fly depending on distance from the model origin, but not sure just yet.

**Comment by dhundaleamol** [comment]
Hi ,

I got some issues to zooming a image on left mouse click .
Its working fine with "handlemousemove()" event with left mouse click.

But I don't want to move mouse every time.I just want to hold left mouse click and it will automatically zooming till I hold left mouse click.

Can you please suggest  me some logic for that . .

**Comment by edocs** [comment]
Hi @dhundaleamol,

That is a preset navigation mode by the looks of things, you should just be able to set `viewer.navigationMode = 'zoom'` - the code for this is in the handleMouseMove function where you should see

```javascript
if (button == 'left') {
	switch (viewer.navigationMode) {
```

**Comment by dhundaleamol** [comment]
Thanx @edocs ,

But , I already did that. I don't want to move mouse .I just want to zooming on long press of left mouse click. (means In a one long press click , counter of DeltaX and DeltaY position will automatically incremented.)
I added the functionality onMouseDown function . But it works on every single click .

If you want to see a demo of walk through option .You can refer a solibri software .
I found a demo of walk through implementation . .

**Comment by edocs** [comment]
Okay my apologies, I now understand what you are after. In the `handleMouseDown` function, you will want to run a `setTimeout(myFunc,50)` and at the end of the `myFunc` function do `if(mouseDown) setTimeout(myFunc,50)`, so that while the mouse is kept pressed the function will run at a 50ms interval (`handleMouseUp()` sets `mouseDown` to false, and will therefore stop any further processing of `myFunc`). The `myFunc` is what will want to run `navigate('zoom'....`. Hope this helps.

**Comment by dhundaleamol** [comment]
Hie Edocs,

I used keyboard functionality (ie._initKeyboardEvents() ) when navigationmode is fly.But when I have pressed a key for a long time and after that release a key .still forward action is calling continuously due to not going a call on keyup function.I am trying this to fix since last two days.

Can you suggest me something on that.

**Comment by LloydPickering** [comment]
Is it by any chance a Focus issue? If you lose focus on the element which is handling the keyboard events, they will stop firing (same with mouse events if you are handling mouse down/up).

If this is the problem, and you are using jQuery, you can check for lost Focus: https://api.jquery.com/focusout/
