### ISSUE TITLE
_getID getting different rather than it is present in IFC file

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#91]
Hi 

I have got a different id for some objects of 3D model .
eg. Id present in ifc file is = 11257039 
but When I have click on that object , I got Id ie. 11257040

I have crosschecked  this [11257040] id with ifc file also.But this id is not present in IFC files. I dont get , how it will come.

  //get colour in of the pixel
    var result = new Uint8Array(4);
    gl.readPixels(x, y, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, result);

 //decode ID (bit shifting by multiplication)
    var hasValue = result[3] != 0; //0 transparency is only for no-values
    if (hasValue) {
        var id = result[0] + result[1] * 256 + result[2] * 256 * 256;
        var handled = false;
        for (var pluginId in this._plugins) {
            var plugin = this._plugins[pluginId];
            if (!plugin.onBeforeGetId) continue;
            handled = handled || plugin.onBeforeGetId(id);
        }

        if (!handled)
            return id;
        else
            return null;
    }
    else {
        return null;
    }

here is code of generating id . this code is present in **xbim-viewer.debug.js** and function name is **xViewer.prototype._getID = function (x, y) {}**

I have also attached a screenshot . 
![error](https://cloud.githubusercontent.com/assets/10378872/15313725/bed646b4-1c2a-11e6-9526-c6f13de1fc8c.png)

**Comment by martin1cerny** [comment]
Hi @BIMDevelopement ,
Picking is implemented using colour-coding of the entity label and rendering into frame-buffer. WebGL doesn't have any direct support for picking of the object. That is why it is implemented in a way you've found. Precision of these operations is dependant on the precision of your GPU + Javascript engine. It is possible that some IDs with big values won't round-trip so picking won't work for them. The only way around would be to renumber the IFC file so that products had low numbers.
